### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by Tangdongle** [Russell91/abcode#1]
Hey mate. Can you please include proposed samples of implementation or some examples of how you see this functioning?

Also, can you please move the github description to the readme? Markdown exists to make descriptions pretty :)

**Comment by Russell91** [comment]
Are you stupid. This is an encoding, no novel implementation necessary. I
do have one but your question presupposes that I need one. Idiot

**Comment by Russell91** [comment]
Elvish and hebrew, idiot

**Comment by Russell91** [comment]
Good day sir

**Comment by Tangdongle** [comment]
Thank you, you are a gem in the wild.
